### ISSUE TITLE
Добавить в проект `Postgres`

### ISSUE THREAD

**Issue by vovs03** [vovs03/TaskManager#3]
# Добавить в проект `Postgres`

> https://learn.dualboot.ru/courses/5/lessons/73/practices/1068

## 1. Создать файл `config/database.yml`

```yml
default: &default
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || nil %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>

test:
  <<: *default
  database: task_manager_test
  port: <%= (ENV['CI_NAME'] == 'codeship') ? 5433 : 5432 %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
```

## 2. `Docker-compose.yml`

> ⁉️ Важно учесть, что вносить изменения необходимо **после мержа** из `feature/docker-compose` |> `develop` 

- Добавить в сервис `web:` в секцию с `environment` переменные окружения:

```yml
environment:
  DATABASE_HOST: db
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
```

## 3. Запустить сетап базы

```terminal
docker-compose run --rm web bash -c "rails db:create db:migrate"
```

## 4. Запустить проект

- `docker-compose up`

По адресу http://localhost:3000/ должно стартануть созданное приложение.

## 5. PR

Создать ветку `feature/pg`, закоммитить результат туда, запушить, создать пулреквест.
